import express from 'express';
import Message from '../models/Message.js';
import User from '../models/User.js';
import { auth } from '../middleware/auth.js';
import { createNotification } from './notifications.js';
import pkg from 'agora-token';
const { RtcTokenBuilder, RtcRole } = pkg;

const router = express.Router();

// @route   GET /api/chat/agora-token
// @desc    Generate secure Agora Token for Video/Audio calls
router.get('/agora-token', auth, (req, res) => {
  const { channelName } = req.query;
  if (!channelName) {
    return res.status(400).json({ message: 'channelName is required' });
  }

  const APP_ID = '0e4a8ef3cd17483bbb29daf1d3b5eca0';
  const APP_CERTIFICATE = 'f8bb51f8a97447d49065d08f2e9b2125';
  const role = RtcRole.PUBLISHER;
  const expirationTimeInSeconds = 3600;
  const currentTimestamp = Math.floor(Date.now() / 1000);
  const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds;

  try {
    // uid 0 allows joining with any random numeric uid generated by Agora client
    const token = RtcTokenBuilder.buildTokenWithUid(
      APP_ID,
      APP_CERTIFICATE,
      channelName,
      0,
      role,
      privilegeExpiredTs
    );
    return res.json({ token });
  } catch (err) {
    console.error('Error generating Agora token:', err);
    return res.status(500).json({ message: 'Failed to generate token' });
  }
});

// @route   GET /api/chat/history/:userId
// @desc    Get message history between current user and specified user
router.get('/history/:userId', auth, async (req, res) => {
  try {
    const messages = await Message.find({
      $or: [
        { senderId: req.user.id, receiverId: req.params.userId },
        { senderId: req.params.userId, receiverId: req.user.id }
      ]
    }).sort({ createdAt: 1 });

    // Mark received messages as read
    await Message.updateMany(
      { senderId: req.params.userId, receiverId: req.user.id, isRead: false },
      { $set: { isRead: true } }
    );

    res.json(messages);
  } catch (error) {
    console.error('Get chat history error:', error);
    res.status(500).json({ message: 'Server error retrieving chat history' });
  }
});

// @route   POST /api/chat/send
// @desc    Save a direct message + push real-time notification to receiver
router.post('/send', auth, async (req, res) => {
  const { receiverId, content } = req.body;
  if (!content) {
    return res.status(400).json({ message: 'Message content is required' });
  }

  try {
    const receiver = await User.findById(receiverId);
    if (!receiver) {
      return res.status(404).json({ message: 'Receiver user not found' });
    }

    const message = new Message({
      senderId: req.user.id,
      receiverId,
      content,
      isRead: false
    });

    await message.save();

    // ── Real-time notification ──────────────────────────────────────────────
    const io = req.app.get('io');
    const senderName = req.user.name || 'Someone';

    // Determine a preview (truncate long messages)
    const preview = content.startsWith('{"attachment":')
      ? 'sent you an attachment'
      : content.length > 60 ? content.slice(0, 60) + '…' : content;

    await createNotification(io, {
      recipientId: receiverId,
      senderId:    req.user.id,
      type:        'message',
      content:     `${senderName} sent you a message: "${preview}"`,
      link:        `/chat/${req.user.id}`
    });
    // ───────────────────────────────────────────────────────────────────────

    res.status(201).json(message);
  } catch (error) {
    console.error('Send message error:', error);
    res.status(500).json({ message: 'Server error saving message' });
  }
});

// @route   GET /api/chat/conversations
// @desc    Get active conversations summary
router.get('/conversations', auth, async (req, res) => {
  try {
    // Find all messages involving current user
    const messages = await Message.find({
      $or: [{ senderId: req.user.id }, { receiverId: req.user.id }]
    }).sort({ createdAt: -1 });

    // Group messages by partner
    const partnerIds = new Set();
    const latestMessages = [];

    for (const msg of messages) {
      const partnerId = msg.senderId.toString() === req.user.id ? msg.receiverId.toString() : msg.senderId.toString();
      if (!partnerIds.has(partnerId)) {
        partnerIds.add(partnerId);
        latestMessages.push(msg);
      }
    }

    // Populate user profiles for partners
    const conversations = await Promise.all(latestMessages.map(async (msg) => {
      const partnerId = msg.senderId.toString() === req.user.id ? msg.receiverId : msg.senderId;
      const partner = await User.findById(partnerId, 'name email avatarUrl role isOnline');
      
      if (!partner) return null;
      
      return {
        id: partnerId.toString(),
        participants: [req.user.id, partnerId.toString()],
        lastMessage: msg,
        partner,
        updatedAt: msg.createdAt
      };
    }));

    res.json(conversations.filter(c => c !== null));
  } catch (error) {
    console.error('Get conversations error:', error);
    res.status(500).json({ message: 'Server error retrieving conversations' });
  }
});

// @route   PUT /api/chat/message/:id
// @desc    Edit a message
router.put('/message/:id', auth, async (req, res) => {
  const { content } = req.body;
  if (!content || !content.trim()) {
    return res.status(400).json({ message: 'Message content is required' });
  }

  try {
    const message = await Message.findById(req.params.id);
    if (!message) {
      return res.status(404).json({ message: 'Message not found' });
    }

    // Check if the current user is the sender
    if (message.senderId.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Unauthorized to edit this message' });
    }

    // Check if original message is an attachment
    if (message.content.trim().startsWith('{"attachment":')) {
      return res.status(400).json({ message: 'Cannot edit an attachment message' });
    }

    // Check if new content tries to be an attachment
    if (content.trim().startsWith('{"attachment":')) {
      return res.status(400).json({ message: 'Cannot change text message to attachment' });
    }

    message.content = content;
    message.isEdited = true;
    await message.save();

    res.json(message);
  } catch (error) {
    console.error('Edit message error:', error);
    res.status(500).json({ message: 'Server error editing message' });
  }
});

// @route   DELETE /api/chat/message/:id
// @desc    Delete a message (completely vanishes)
router.delete('/message/:id', auth, async (req, res) => {
  try {
    const message = await Message.findById(req.params.id);
    if (!message) {
      return res.status(404).json({ message: 'Message not found' });
    }

    // Check if the current user is the sender
    if (message.senderId.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Unauthorized to delete this message' });
    }

    await Message.findByIdAndDelete(req.params.id);

    res.json({ message: 'Message deleted successfully' });
  } catch (error) {
    console.error('Delete message error:', error);
    res.status(500).json({ message: 'Server error deleting message' });
  }
});

export default router;
